---
- name: Setup for Nginx installation
  become: yes
  template:
    src: ../templates/nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo

- name: Installation Nginx
  become: yes
  with_items: "{{ centos_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: Start Nginx
  become: yes
  service:
    name: nginx
    state: started
