---
- name: Installation Nginx
  become: yes
  with_items: "{{ fedora_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: Start Nginx
  become: yes
  service:
    name: nginx
    state: started
