---
- name: Before install PHP Update
  become: yes
  shell: apt update

- name: Installation PHP
  become: yes
  with_items: "{{ ubuntu_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest
